version: "3.8"
services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/usr/src/app
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
